#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env.render}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# Local helper (specific to this wizard): print a value straight out of the
# project's own .env.local so nothing sensitive gets hardcoded into this
# script — it only ever reads your existing local file.
# ──────────────────────────────────────────────────────────────────────────
show_local() {
  local key="$1" val
  val=$(grep -E "^${key}=" .env.local 2>/dev/null | head -n1 | cut -d= -f2-)
  if [[ -z "$val" ]]; then
    warn "$key not found in .env.local — check it manually"
  else
    printf '  %s%s%s = %s%s%s\n' "$BOLD" "$key" "$RESET" "$GREEN" "$val" "$RESET"
  fi
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "iSN Compass → Render go-live"

# ── Stage 1: create the Web Service ────────────────────────────────────────
stage "Create the Render Web Service"
say "This creates the app itself on Render, connected to your GitHub repo."
open_url "https://dashboard.render.com/create?type=web"
step "Connect your GitHub account if you haven't, then pick the repo: isngs-dev/ISN_Compass"
step "Branch: main"
step "Name: whatever you like, e.g. isn-compass (this becomes part of the URL)"
step "Runtime: Node"
step "Build Command: pnpm install && pnpm build"
step "Start Command: pnpm start"
note "Render may offer a Dockerfile / auto-detected settings instead — Node + those two commands is the target either way."
warn "The first deploy will likely fail or crash at runtime — that's expected, no env vars are set yet. Fix that next."
pause "Created the service and kicked off the first deploy?"

# ── Stage 2: env vars that don't depend on the Render URL ─────────────────
stage "Set the env vars that are already known"
say "These are the same values already in your local .env.local — copy each one"
say "into Render: your service → Environment → Add Environment Variable."
echo
show_local NEXT_PUBLIC_SUPABASE_URL
show_local NEXT_PUBLIC_SUPABASE_ANON_KEY
show_local SUPABASE_SERVICE_ROLE_KEY
show_local DATABASE_URL
show_local RESEND_API_KEY
show_local EMAIL_FROM
show_local ADMIN_EMAIL
show_local CRON_SECRET
echo
warn "Do NOT set NEXT_PUBLIC_SITE_URL yet — you don't know the Render URL until the next stage."
pause "Added all 8 of those in Render's Environment tab?"

# ── Stage 3: the URL-dependent one, then a fresh deploy ────────────────────
stage "Set NEXT_PUBLIC_SITE_URL and redeploy"
say "This one is the value that broke things before on Vercel when it was left"
say "pointing at localhost — get it right here."
step "On your Render service's page, copy the URL shown at the top (https://<name>.onrender.com)"
ask RENDER_URL "Paste the Render URL:"
write_env RENDER_URL "$RENDER_URL"
echo
say "Add this env var in Render:"
printf '  %sNEXT_PUBLIC_SITE_URL%s = %s%s%s\n' "$BOLD" "$RESET" "$GREEN" "$RENDER_URL" "$RESET"
echo
warn "NEXT_PUBLIC_* vars are baked in at build time — saving the env var alone is not enough."
step "Go to Manual Deploy → Deploy latest commit to force a fresh build with it included."
pause "Redeployed after setting NEXT_PUBLIC_SITE_URL?"

# ── Stage 4: verify the web service is actually up ─────────────────────────
stage "Verify the site is live"
open_url "$RENDER_URL"
step "Confirm the login page loads (not an error page)."
step "Sign in with the same Admin email/password you already use on Supabase — that account didn't move."
step "Confirm the dashboard loads with all-zero counts (the database was wiped clean for launch)."
pause "Logged in and dashboard looks right?"

# ── Stage 5: the reminder cron, as a SEPARATE Render resource ──────────────
stage "Create the reminder Cron Job (separate from the web service)"
say "Render has no equivalent of vercel.json's cron — the daily reminder email"
say "needs its own Cron Job resource that just hits your app's endpoint."
open_url "https://dashboard.render.com/create?type=cron"
step "Repo: isngs-dev/ISN_Compass, branch main (same repo, different resource type)"
note "Render may ask for a runtime/build step even though this doesn't run the app — a trivial build command like 'true' or 'echo ok' is fine, the command below is all that matters."
step "Schedule: 0 8 * * *  (this runs in UTC on Render — adjust the hour for your timezone)"
step "Command:"
printf '    %scurl -fsS -X GET "%s/api/cron/reminders" -H "Authorization: Bearer $CRON_SECRET"%s\n' "$DIM" "$RENDER_URL" "$RESET"
step "Add CRON_SECRET as an env var on this Cron Job too (same value as the web service's)."
pause "Cron Job created and saved?"

# ── Stage 6: end-to-end test on the real deployment ─────────────────────────
stage "End-to-end test on Render"
say "Prove the whole loop works on the new host, not just that it loads."
step "In the app: create a department, then a team member using an email you can check."
step "Create an initiative, then a task under it assigned to that team member."
step "Open that email — confirm the link in it points at $RENDER_URL, not localhost."
step "Click Confirm Completion, then check the task shows Completed on the dashboard."
pause "All of that worked end to end?"

# ── Stage 7: decide what happens to Vercel ─────────────────────────────────
stage "Retire or keep Vercel"
say "Render is now live. Decide what to do with the old Vercel deployment:"
step "Keep both running for a while, or"
step "Remove Vercel's env vars / pause the project, or"
step "If you have a custom domain, point its DNS at Render instead of Vercel."
note "Nothing here is scripted — it's a judgment call once you're confident in Render."

finish
say "Go-live checklist done. This script (deploy-to-render.sh) and .env.render"
say "(just the Render URL, nothing secret) can be deleted once you're confident."
